name: Emergency-Dashboard

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: emergency-trial

    env_file:
      - .env

    environment:
      PORT: "5053"

    ports:
      - "${APP_PORT:-5053}:5053"

    restart: unless-stopped